### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by softloud** [softloud/adpain#20]
Rebooted plan

- [x] all datasets used in analysis in same gs
- [ ] labels complete
- [x] joining datasets in worksheets

**Comment by softloud** [comment]
@HollieBirkinshaw Scales have been [copied in](https://docs.google.com/spreadsheets/d/1CMsqvOC3SteW1FsSomyfSAYSXRspuU17PWNJbrKRZKk/edit#gid=91269315) for you to label with direction of improvement and lower and upper bounds (not entirely sure we need these so don't fuss about it if a massive hassle). Direction of improvement is the main one. I am currently converting the means with direction of improvement in the opposite direction to a negative value to invert the score (Lisa's recommendation).

**Comment by softloud** [comment]
@HollieBirkinshaw Taking a look at the `r` values this morning. Do they need to be converted with this dataset? Is `n` the sample size now for these?

**Comment by softloud** [comment]
@HollieBirkinshaw In the Arnold 2012: 1 study there are some negative standard deviations. Could you double check these for me? Standard deviation should always be a positive number. If they were reported negative, I suppose we'll have to assume it's a typo and remove the minus sign. 

![image](https://user-images.githubusercontent.com/13408706/134768544-72362cb9-f396-4a7b-907b-0bea7f4a6bff.png)

**Comment by softloud** [comment]
NB: to be documented in write up. 

Where standard deviation and standard error were not reported but confidence interval, mean, and sample size were, it was assumed the confidence interval was a 95% confidence interval, and the standard deviation was calculated thus:

sd = (upper confidence interval - mean) / (quantile fn of standard normal evaluated at 1-0.05/2 * sqrt of sample size ) 
```
ci_upper - mean) / (qnorm(1 - 0.05/2) * sqrt(n))
```

**Comment by HollieBirkinshaw** [comment]
> @HollieBirkinshaw In the Arnold 2012: 1 study there are some negative standard deviations. Could you double check these for me? Standard deviation should always be a positive number. If they were reported negative, I suppose we'll have to assume it's a typo and remove the minus sign.
> 
> ![image](https://user-images.githubusercontent.com/13408706/134768544-72362cb9-f396-4a7b-907b-0bea7f4a6bff.png)

fixed, my mistake, copied and pasted into the wrong column 🤦‍♀️

**Comment by softloud** [comment]
@HollieBirkinshaw A record to look into. 

In Covidence the value 0.22 is listed as a standard deviation, but is recorded as standard error. Should I go ahead and change things like this as I come across them, or ping you to check?

gs_row refers to the current row in the google sheet

![image](https://user-images.githubusercontent.com/13408706/134939239-a3d77c91-30c1-4875-a8f2-ca1305b3f5d3.png)

**Comment by HollieBirkinshaw** [comment]
> @HollieBirkinshaw A record to look into.
> 
> In Covidence the value 0.22 is listed as a standard deviation, but is recorded as standard error. Should I go ahead and change things like this as I come across them, or ping you to check?
> 
> gs_row refers to the current row in the google sheet
> 
> ![image](https://user-images.githubusercontent.com/13408706/134939239-a3d77c91-30c1-4875-a8f2-ca1305b3f5d3.png)

ping me, cause covidence isn't straightforward 😅 do you remember me saying that you couldn't have different statistics for baseline and post-intervention scores for the same outcome in covidence? this is the case with almost every change score - they reported mean and SD at baseline, but mean change and SE at post-intervention. When this is the case we wrote it in the description, here you can see that although the column is SD, in the description we wrote "LS mean, SE from baseline" to denote that the values are actually mean change and SE, not SD:

![image](https://user-images.githubusercontent.com/79980803/134940440-729c0a37-6835-44ea-90a0-5433c78e51ad.png)

**Comment by softloud** [comment]
In the Allen 2014 substantial pain reduction records, the percentages match, but the sample sizes are slightly 
![image](https://user-images.githubusercontent.com/13408706/134942685-26b3556a-ce02-4c89-8d16-9ed0349b313e.png)
less. 
![image](https://user-images.githubusercontent.com/13408706/134942733-7bcb5672-2f9d-4a5e-b9e3-a8b793eda1c3.png)
Is this because of drop outs?

**Comment by softloud** [comment]
> > @HollieBirkinshaw A record to look into.
> > In Covidence the value 0.22 is listed as a standard deviation, but is recorded as standard error. Should I go ahead and change things like this as I come across them, or ping you to check?
> > gs_row refers to the current row in the google sheet
> > ![image](https://user-images.githubusercontent.com/13408706/134939239-a3d77c91-30c1-4875-a8f2-ca1305b3f5d3.png)
> 
> ping me, cause covidence isn't straightforward sweat_smile do you remember me saying that you couldn't have different statistics for baseline and post-intervention scores for the same outcome in covidence? this is the case with almost every change score - they reported mean and SD at baseline, but mean change and SE at post-intervention. When this is the case we wrote it in the description, here you can see that although the column is SD, in the description we wrote "LS mean, SE from baseline" to denote that the values are actually mean change and SE, not SD:
> 
> ![image](https://user-images.githubusercontent.com/79980803/134940440-729c0a37-6835-44ea-90a0-5433c78e51ad.png)

:joy: Covidence not straightforward, indeed! Glad it's right.

**Comment by softloud** [comment]
## scrape nma-specific 

- [x] update read gs script
- [x] check outcome labels
- [x] remove mood hierarchy code
- [x] render site

**Comment by softloud** [comment]
w00t @HollieBirkinshaw NMA data imported and we are done with making analysis dataset for now
